export const x = [
  {
    adult: false,
    backdrop_path: "/snlu32RmjldF9b068UURJg8sQtn.jpg",
    genre_ids: [28, 80, 14],
    id: 414,
    original_language: "en",
    original_title: "Batman Forever",
    overview:
      "Batman must battle a disfigured district attorney and a disgruntled former employee with help from an amorous psychologist and a young circus acrobat.",
    popularity: 21.665,
    poster_path: "/mzzNBVwTiiY94xAXDMWJpNPW2US.jpg",
    release_date: "1995-06-16",
    title: "Batman Forever",
    video: false,
    vote_average: 5.401,
    vote_count: 4554,
    watched: false,
    trueIndex: 15,
    display: false,
  },
  {
    adult: false,
    backdrop_path: "/1YaG52CwGY3pKh76OBlwX0ymncg.jpg",
    genre_ids: [878, 28, 16, 9648],
    id: 123025,
    original_language: "en",
    original_title: "Batman: The Dark Knight Returns, Part 1",
    overview:
      "Batman has not been seen for ten years. A new breed of criminal ravages Gotham City, forcing 55-year-old Bruce Wayne back into the cape and cowl. But, does he still have what it takes to fight crime in a new era?",
    popularity: 22.889,
    poster_path: "/kkjTbwV1Xnj8wBL52PjOcXzTbnb.jpg",
    release_date: "2012-08-21",
    title: "Batman: The Dark Knight Returns, Part 1",
    video: false,
    vote_average: 7.748,
    vote_count: 1341,
    watched: false,
    trueIndex: 16,
    display: false,
  },
  {
    adult: false,
    backdrop_path: "/m4UT6yKXhXgbzxpeV35L4jLoJoP.jpg",
    genre_ids: [28, 878, 12, 35],
    id: 415,
    original_language: "en",
    original_title: "Batman & Robin",
    overview:
      "Batman and Robin deal with relationship issues while preventing Mr. Freeze and Poison Ivy from attacking Gotham City.",
    popularity: 23.078,
    poster_path: "/cGRDufDDSrFrv7VI4YnmWnslne0.jpg",
    release_date: "1997-06-20",
    title: "Batman & Robin",
    video: false,
    vote_average: 4.322,
    vote_count: 4404,
    watched: false,
    trueIndex: 17,
    display: false,
  },
  {
    adult: false,
    backdrop_path: "/3xnfbtgJmVotajqM57iKib3ftnT.jpg",
    genre_ids: [878, 80, 28, 16, 9648],
    id: 40662,
    original_language: "en",
    original_title: "Batman: Under the Red Hood",
    overview:
      "One part vigilante, one part criminal kingpin, Red Hood begins cleaning up Gotham with the efficiency of Batman, but without following the same ethical code.",
    popularity: 21.848,
    poster_path: "/7lmHqHg1rG9b4U8MjuyQjmJ7Qm0.jpg",
    release_date: "2010-07-27",
    title: "Batman: Under the Red Hood",
    video: false,
    vote_average: 7.788,
    vote_count: 1371,
    watched: false,
    trueIndex: 18,
    display: false,
  },
  {
    adult: false,
    backdrop_path: null,
    genre_ids: [18],
    id: 148918,
    original_language: "ro",
    original_title: "Superman, Spider-Man sau Batman",
    overview:
      "Aron, a 5-year-old boy, sets together with his worried father on a journey at the end of which he wishes, like the superheroes in the comic books, to save his mother suffering from a heart condition.",
    popularity: 1.967,
    poster_path: "/iUp85s5s7eaPbuCUNqOCeJCEVpY.jpg",
    release_date: "2011-06-01",
    title: "Superman, Spider-Man or Batman",
    video: false,
    vote_average: 6.7,
    vote_count: 14,
    watched: false,
    trueIndex: 19,
    display: false,
  },
];
